// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCItb9sjJFqFBGzVyq9Fo3cRxjPxoj5neQ',
    appId: '1:331507073845:web:ccabe05167f4d76108c27c',
    messagingSenderId: '331507073845',
    projectId: 'lasttry-9fd9d',
    authDomain: 'lasttry-9fd9d.firebaseapp.com',
    storageBucket: 'lasttry-9fd9d.appspot.com',
    measurementId: 'G-DPVC3BC0MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ScUonPbWDDymh1IPm1CFryp4tlo3Rbk',
    appId: '1:331507073845:android:996ba0ce52ef00bc08c27c',
    messagingSenderId: '331507073845',
    projectId: 'lasttry-9fd9d',
    storageBucket: 'lasttry-9fd9d.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDgsxFeqSNVNX0lBHNvtV65Qtm3-WrWdQ',
    appId: '1:331507073845:ios:fe0e755c9dd35e6608c27c',
    messagingSenderId: '331507073845',
    projectId: 'lasttry-9fd9d',
    storageBucket: 'lasttry-9fd9d.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDgsxFeqSNVNX0lBHNvtV65Qtm3-WrWdQ',
    appId: '1:331507073845:ios:fe0e755c9dd35e6608c27c',
    messagingSenderId: '331507073845',
    projectId: 'lasttry-9fd9d',
    storageBucket: 'lasttry-9fd9d.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCItb9sjJFqFBGzVyq9Fo3cRxjPxoj5neQ',
    appId: '1:331507073845:web:b5461c87c508538108c27c',
    messagingSenderId: '331507073845',
    projectId: 'lasttry-9fd9d',
    authDomain: 'lasttry-9fd9d.firebaseapp.com',
    storageBucket: 'lasttry-9fd9d.appspot.com',
    measurementId: 'G-Z5Z6JRSKXQ',
  );

}